keys:
  - &host_sid age1ytfze9tv5l80ujqfd66xp97w2u0lq8jrx45ulf0szey8ny0t837sdktdzf
  - &host_rx4 age1ytfze9tv5l80ujqfd66xp97w2u0lq8jrx45ulf0szey8ny0t837sdktdzf
  - &host_vde age1mc07jayz4dpwenh06fzlcgfzk5t7ln0z3n65emwlm5r7nq59m4jstd7y8u
  - &user_sid age19yeqvv28fgrtk6jsh3xyaf0lch86kna6rcz4dwe962yyyyevu30sx474xy
creation_rules:
  - path_regex: hosts/sid/secrets/secrets.yaml$
    key_groups:
      - age:
          - *user_sid
          - *host_sid
  - path_regex: hosts/rx4/secrets/secrets.yaml$
    key_groups:
      - age:
          - *user_sid
          - *host_rx4
  - path_regex: hosts/vde/secrets/secrets.yaml$
    key_groups:
      - age:
          - *user_sid
          - *host_vde
