keys:
  - &host_16ach6 age1km907lx69fwvmwgt7rspkuyxtkdrhr7r7t0mw20e5rymsu364exs3rl28q
  - &host_sid age1ytfze9tv5l80ujqfd66xp97w2u0lq8jrx45ulf0szey8ny0t837sdktdzf
  - &host_rv2 age1j6s2ec3ltm9004fhvmd7xqq0zna2fr4m8kw4f235r9k0hfryjctq050vs2
  - &host_rx4 age10mkn2jgwpue7gy92vwjqp4j4j9qyh5enrzw8j82v872yflawvvkqhqde34
  - &host_vde age1mc07jayz4dpwenh06fzlcgfzk5t7ln0z3n65emwlm5r7nq59m4jstd7y8u
  - &user_sid age19yeqvv28fgrtk6jsh3xyaf0lch86kna6rcz4dwe962yyyyevu30sx474xy
creation_rules:
  - path_regex: hosts/16ach6/secrets/secrets.yaml$
    key_groups:
      - age:
          - *user_sid
          - *host_16ach6
  - path_regex: hosts/sid/secrets/secrets.yaml$
    key_groups:
      - age:
          - *user_sid
          - *host_sid
  - path_regex: hosts/rv2/secrets/secrets.yaml$
    key_groups:
      - age:
          - *user_sid
          - *host_rv2
  - path_regex: hosts/rx4/secrets/secrets.yaml$
    key_groups:
      - age:
          - *user_sid
          - *host_rx4
  - path_regex: hosts/vde/secrets/secrets.yaml$
    key_groups:
      - age:
          - *user_sid
          - *host_vde
  - path_regex: users/sid/home/secrets/secrets.yaml$
    key_groups:
      - age:
          - *user_sid
